[package]
name = "image-to-ascii"
version = "0.1.0"
authors = ["Niklas Treml <treml.niklas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image_to_ascii = {path = "./src/image_to_ascii"}